### ISSUE TITLE
Valve became `!Sync` between 0.6.2 and 0.7

### ISSUE THREAD

**Issue by bbqsrc** [jonhoo/stream-cancel#12]
Was this intentional? It seems that [this commit](https://github.com/jonhoo/stream-cancel/commit/7de47b06af354f2d831a84151483166f0ae91423) causes the change though it's non-obvious to me why.

I am asking because it broke my code. 😄

**Comment by jonhoo** [comment]
Ah, no, that was not intentional! I believe that should be fixable by adding `+ Sync` to
https://github.com/jonhoo/stream-cancel/blob/bdc6ef06a52e770d2863f2471c8dfccbe9f7c202/src/combinator.rs#L117

Would you mind opening a PR?

**Comment by bbqsrc** [comment]
#13 😄
