### ISSUE TITLE
rust futures 0.3.5

### ISSUE THREAD

**Issue by pavlik-uhuhu** [jonhoo/stream-cancel#5]
Hello, current version of rust futures 0.3.5 has new version of StreamExt trait with new method _take_until_:
https://docs.rs/futures/0.3.5/futures/stream/trait.StreamExt.html#method.take_until

So with current version of futures, when yours StreamExt trait and rust-futures StreamExt are in scope together, _take_until_ method has to be explicitly specified.
So maybe this create's combinator method has to be renamed?

**Comment by jonhoo** [comment]
Oh, good catch! Unfortunately, renaming is a breaking change, so released as `0.6.1`.
